version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: back_app_alliar
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    depends_on:
      - mongo
    restart: always
    links:
      - mongo

  mongo:
    image: mongo:4.4.4
    ports:
      - 27017:27017
    volumes:
      - .docker/dbdata:/data/db
    environment:
      - MONGO_INITDB_DATABASE=alliar

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
